#ifndef __RENALIBS_RENAAPA_ERRCODES_H__
#define __RENALIBS_RENAAPA_ERRCODES_H__

#define RENA_ERR_ILLEGAL_VALUE_STRING                   0x000001
#define RENA_ERR_SET_SIGNED_VALUE_TO_UNSIGNED_TYPE      0x000002
#define RENA_ERR_CONVERT_LARGE_NUMBER_TO_SMALLER_TYPE   0x000003

#define RENA_ERR_DIGIT_SET_VALUE_MORE_THAN_ONE_DIGIT    0x000100

#define RENA_ERR_ARITHMETIC_OVERFLOW                    0x010000
#define RENA_ERR_ARITHMETIC_DIVIDED_BY_ZERO             0x010001

#endif // __RENALIBS_RENAAPA_ERRCODES_H__
