#ifndef __RENALIBS_RENAAPA_ERRCODES_H__
#define __RENALIBS_RENAAPA_ERRCODES_H__

#define RENA_ERR_ILLEGAL_VALUE_STRING                   0x0001
#define RENA_ERR_SET_SIGNED_VALUE_TO_UNSIGNED_TYPE      0x0002

#define RENA_ERR_DIGIT_SET_VALUE_MORE_THAN_ONE_DIGIT    0x0100

#endif // __RENALIBS_RENAAPA_ERRCODES_H__
